name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
        
        - ad: .NET Core SDK Kurulumu
   kullanır: eylemler/kurulum-dotnet@v1.9.0
   ile birlikte:
     # Kullanılacak isteğe bağlı SDK sürümleri.  Sağlanmamışsa, mevcut olduğunda global.json sürümünü yükleyecektir.  Örnekler: 2.2.104, 3.1, 3.1.x
     dotnet sürümü: # isteğe bağlı
     # Kimlik doğrulamasının ayarlanacağı isteğe bağlı paket kaynağı.  Deponun kökündeki mevcut herhangi bir NuGet.config'e danışacak ve bir ClearTextPassword olarak NUGET_AUTH_TOKEN ortam değişkenini kullanarak geçici bir NuGet.config sağlayacaktır.
     kaynak-url: # isteğe bağlı
     # Mevcut havuzun sahibi dışındaki GitHub Paket Kaydı kuruluşlarından/kullanıcılarından paketleri kullanmak için isteğe bağlı SAHİBİ.  Yalnızca kaynak-url'de bir GPR URL'si sağlanmışsa kullanılır
     sahip: # isteğe bağlı
     # NuGet.config dosyanız deponun kökünde yer almıyorsa, isteğe bağlı NuGet.config konumu.
     yapılandırma dosyası: # isteğe bağlı
     # Yayın öncesi sürümlerin kesin olmayan sürümlerle eşleştirilip eşleşmeyeceği (örneğin, 5.0.0-preview.6'nın 5, 5.0, 5.x veya 5.0.x ile eşleştirilmesi).  Sağlanmadığı takdirde varsayılan olarak false olur.
     dahil-ön yayın: # isteğe bağlı 
