name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        
        pytest
- isim: Önbellek
   kullanır: eylemler/önbellek@v2.1.7
   ile birlikte:
     # Önbelleğe alınacak ve geri yüklenecek dosyaların, dizinlerin ve joker karakter kalıplarının listesi
     yol: 
     # Önbelleği geri yüklemek ve kaydetmek için açık bir anahtar
     anahtar: 
     # Anahtar için önbellek isabeti gerçekleşmediyse, önbelleği geri yüklemek için kullanılacak sıralı bir anahtar listesi
     geri yükleme tuşları: # isteğe bağlı
     # Yükleme sırasında büyük dosyaları bayt olarak bölmek için kullanılan yığın boyutu
     yükleme yığını boyutu: # isteğe bağlı 
